# Generated by Django 3.2 on 2021-05-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TolusBlog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
